### ISSUE TITLE
N64SoundListTool - Extracted sound decoding failed - Star Wars Rogue Squadron

### ISSUE THREAD

**Issue by JackCarterSmith** [jombo23/N64-Tools#47] opened 2022-10-05 20:04 UTC
Hi,

I'm not sure about doing thing correctly:
I used a RS-N64_USA rom with N64SoundListTool (using master ([71ecb5e](https://github.com/jombo23/N64-Tools/commit/71ecb5e49d8920dcc7e5fcfbf56ea5e9ab4074e2)) version and latest release from march 11th) and all the sound seem "badly" decoded (see in linked file).
[ExtractedSound.zip](https://github.com/jombo23/N64-Tools/files/9718641/ExtractedSound.zip)

I'm not sure if it's me who doesn't set a parameter correctly or if it's my file who doesn't work.

Anyone can give me a tips please?

**Comment by SubDrag** [comment] 2022-10-10 23:37
You have a mismatched ROM.  Make sure you download the correct one.   I verified the Rogue Squadron sound against ROM with MD5 of:
[47CAC4E2A6309458342F21A9018FFBF0]
Good Name=Star Wars - Rogue Squadron (U) (M3) [!].z64
Header Code=66A24BEC-2EADD94F-C45

Sounds correct, yours is parsing garbage data.

**Comment by JackCarterSmith** [comment] 2022-10-11 08:27
That's my conclusion for now, wrong ROM... But I can't found a good one on www. (So bad I can't dump my own cartridge x)

Instead, I'm managed to use your MORTDecoder class standalone with raw data from PC version. I discuss it in another post of RS datas parsing (https://github.com/dpethes/rerogue/issues/13).
That's work great! But I found some bugs/missing features in it (with PC version):
- 8000/16000 samplerate switching (fixed)
- duplication glitch at start of all long speechs (not present in shortness file) (in progress)

I'm not sure about the 8000/16000 samplerate switch is present/necessary on N64 ROM version, I can't test it for now, but the question is still opened.

**Comment by SubDrag** [comment] 2022-10-11 23:20
Duplication might mean it's running over the same section more than once (not sure).  If you give me a sample sound that's off, can compare to N64 rip.  You should with all the Rogue Squadron N64 versions being supported...find one valid ROM to test with N64 Sound Tool, I'd think, to compare and see running code.

**Comment by SubDrag** [comment] 2022-10-11 23:40
OK I was just starting output at the wrong spot - fix is here, all rips should be good now.
https://github.com/jombo23/N64-Tools/commit/4fe107327f8a602097bed6ab57374612dc4d707a
[Sound05Corrected.zip](https://github.com/jombo23/N64-Tools/files/9760334/Sound05Corrected.zip)

**Comment by SubDrag** [comment] 2022-10-11 23:43
I'll close this thread as I believe the issue is fixed and can track PC work on your github issue - I don't find any sounds the wrong sample rate on N64 rip.  They all seem 8000 (probably to save space).

**Closed by SubDrag** 2022-10-11 23:43 UTC

**Comment by JackCarterSmith** [comment] 2022-10-12 18:10
Yes I don't think the MORT decoder is broked (for N64 and PC).
Probably a wrong configuration of my MSVC toolchain/toolset...

> I'll close this thread as I believe the issue is fixed and can track PC work on your github issue - I don't find any sounds the wrong sample rate on N64 rip. They all seem 8000 (probably to save space).

You right I presume, even textures have been resized in N64 version. And if the game use programmable RSP chip on N64 for HW accelerated decoding, all make sense!

> OK I was just starting output at the wrong spot - fix is here, all rips should be good now. See this commit on what you should also change: [4fe1073](https://github.com/jombo23/N64-Tools/commit/4fe107327f8a602097bed6ab57374612dc4d707a) 

Great I've tried to remove ~0.5s of sound in wav file before, but you made a proper way to do! Thanks, it's running pretty good now. 
I can't try with N64 file, but for the issue about MORT decoder, it's okay for me now 👍

**Comment by SubDrag** [comment] 2022-10-12 23:13
I found some 16000 sounds in N64 (well the one you posted), so they do exist, I just hadn't noticed before.  I'm not sure why you're having issues, I think the best explanation is you still don't have a valid ROM matching MD5, so it's parsing over junk data.

**Comment by JackCarterSmith** [comment] 2022-10-13 07:43
Do you have something like a flag to know if the sound is 8000 or 16000 in N64 datas?
I've .n64 type file, should I need to find a .z64 one?

**Comment by SubDrag** [comment] 2022-10-13 09:37
I had mentioned in other thread. It's at offset 6 the sampling rate.

**Comment by SubDrag** [comment] 2022-10-13 09:38
Just find a valid rom matching md5 or try another region.
